### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by DINness** [kcaf/PokeRadar#32]
Hi, I apologize for my bad english.
I have a problem with pokeradar+resoursepack's, When I turn on the resource pack, then I get an error.
Do not look at Client fixer, I deleted it and still had an error with resourece pack+pokeradar.

Crash-report this:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ClientFixer (clientfixer-1.4.jar)
  PokeradarLoadingPlugin (pokeradar-3.8.0.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 18.02.18 16:17
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:280)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1882811224 bytes (1795 MB) / 4686499840 bytes (4469 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 5 total; -Xmx6144M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_E3 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	ClientFixer{1.4} [ClientFixer] (minecraft.jar) 
	UCHIJAAAA	backpack{3.0.1} [Backpack] (backpack_3.0.1_1.10.2.jar) 
	UCHIJAAAA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(21jul17).jar) 
	UCHIJAAAA	pixelmon{1.3.2} [Pixelmon] (PixelmonGenerations-1.3.2.jar) 
	Loaded coremods (and transformers): 
ClientFixer (clientfixer-1.4.jar)
  com.gamerforea.clientfixer.asm.ASMTransformer
PokeradarLoadingPlugin (pokeradar-3.8.0.jar)
  pokeradar.asm.AllowedCharactersTransformer
  pokeradar.asm.UnlimitedCharactersTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['DINness'/36, l='Реборн', x=-5064,66, y=70,00, z=-950,48]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by kcaf** [comment]
Pokeradar 3.8.0 is an older version. Try updating pokeradar first and see if the problem persists.

**Comment by DINness** [comment]
I installed the new version and with it the error appears more often, therefore I play with the old version

**Comment by kcaf** [comment]
What resource pack are you using that causes the issue?

**Comment by DINness** [comment]
With LoKiCraft PureCartoonPack 0.2.1c [128x] [1.10], with pokepack 3d, in general with everyone.
The error immediately appears when I switch textures, or when I play the shaders, it does not appear in the main menu

**Comment by kcaf** [comment]
What other mods are you running? Something is conflicting with the EntityRenderer which leads me to believe you have another map mod installed.

**Comment by DINness** [comment]
D:\Games\.minecraft GENERATIONS\mods
backpack_3.0.1_1.10.2
BetterFps-1.4.5-1.10
clientfixer-1.4
CustomNPCs_1.10.2(21jul17)
forge_1.10.2_12.18.3.2254_installer
OptiFine_1.10.2_HD_U_E3
PixelmonGenerations-1.3.2
pokeradar-1-10-2-3.10.1
