### ISSUE TITLE
Game Crashes After Loading Into a Server

### ISSUE THREAD

**Issue by Daoxis** [kcaf/PokeRadar#39]
The mod worked perfectly the first few times I used it. But the first time I placed a custom marker, the game crashed. A popup appears in the Launcher page saying that "It looks like you are using an unsupported or modified version of the game."

Below that, another line says "The game crashed whilst registering a texture" and "The game crashed whilst unexpected error
Error: java.lang.StringIndexOutOfBoundsException: String index out of range: -1"

This issue occurs when joining both a Single-player and Multiplayer server.

What (if anything) can I do to fix this?

![image](https://user-images.githubusercontent.com/37788011/37885582-e1b7e9fc-306a-11e8-8293-999407786429.png)

**Comment by kcaf** [comment]
I need the full crash log to figure out what's going on. Please attach that.

**Comment by Daoxis** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  PokeradarLoadingPlugin (pokeradar-1-12-2-4.2.0 (1).jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 3/26/18 5:28 PM
Description: Unexpected error

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1954)
	at pokeradar.util.Utils.getWorldName(Utils.java:185)
	at pokeradar.Mw.load(Mw.java:376)
	at pokeradar.Mw.onTick(Mw.java:492)
	at pokeradar.forge.EventHandler.renderMap(EventHandler.java:137)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_93_EventHandler_renderMap_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:904)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:348)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:141)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.String.substring(String.java:1954)
	at pokeradar.util.Utils.getWorldName(Utils.java:185)
	at pokeradar.Mw.load(Mw.java:376)
	at pokeradar.Mw.onTick(Mw.java:492)
	at pokeradar.forge.EventHandler.renderMap(EventHandler.java:137)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_93_EventHandler_renderMap_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:904)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:348)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:141)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DAOXIS'/4808, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['DAOXIS'/4808, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.12-SNAPSHOT:ae1eabc:170)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 378559312 bytes (361 MB) / 922746880 bytes (880 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2624 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                              | Signature                                |
	|:------ |:----------------- |:------------ |:----------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft         | 1.12.2       | minecraft.jar                       | None                                     |
	| UCHIJA | mcp               | 9.42         | minecraft.jar                       | None                                     |
	| UCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.2.2624.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge             | 14.23.2.2624 | forge-1.12.2-14.23.2.2624.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | mercurius_updater | 1.0          | MercuriusUpdater-1.12.2.jar         | None                                     |
	| UCHIJA | pixelmon          | 6.2.3        | Pixelmon-1.12.2-6.2.3-universal.jar | None                                     |

	Loaded coremods (and transformers): 
PokeradarLoadingPlugin (pokeradar-1-12-2-4.2.0 (1).jar)
  pokeradar.asm.AllowedCharactersTransformer
  pokeradar.asm.UnlimitedCharactersTransformer
  pokeradar.asm.SimpleWrapperTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 387.95' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2624
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 387.95, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz


Hope this makes sense to you... Thank you!

**Comment by kcaf** [comment]
As far as I can tell there is a strange character in the server name that is blowing up the save file. Try connecting to a different server and see if it works

**Comment by Daoxis** [comment]
Yup, that worked! I have no idea how you would possibly know how to fix my issue, but Im very impressed! You are a very skilled modder and Id love to see what else you can do in the future!

Thanks again!

**Comment by kcaf** [comment]
Glad it hear it worked out. Have fun!
